In [30]:
import pandas as pd
import numpy as np
import seaborn as sns

In [31]:
dt = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [32]:
x_treino = dt[[ "Cover_Type","Elevation","Aspect","Slope", "Horizontal_Distance_To_Hydrology",
                "Vertical_Distance_To_Hydrology", "Horizontal_Distance_To_Roadways", "Hillshade_9am",
                "Hillshade_Noon", "Hillshade_3pm", "Horizontal_Distance_To_Fire_Points", "Wilderness_Area1",
                "Wilderness_Area2", "Wilderness_Area3", "Wilderness_Area4"]] 

tipo_cobert = dt[["Cover_Type"]]

In [33]:
x_treino.corr()

,Cover_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
Cover_Type,1.000000,0.016090,0.008015,0.087722,-0.010515,0.075647,-0.105662,-0.010286,-0.098905,-0.053399,-0.089389,-0.230117,0.014994,0.122146,0.075774
Elevation,0.016090,1.000000,-0.011096,-0.312640,0.412712,0.122092,0.578659,0.097900,0.215782,0.089518,0.443563,0.330417,0.261729,0.354025,-0.783651
Aspect,0.008015,-0.011096,1.000000,0.028148,0.040732,0.056412,0.066184,-0.593997,0.324912,0.635022,-0.052169,-0.131262,0.028238,0.032578,0.075228
Slope,0.087722,-0.312640,0.028148,1.000000,-0.055976,0.265314,-0.277049,-0.200072,-0.612613,-0.326887,-0.239527,-0.152820,-0.065923,-0.113033,0.286985
Horizontal_Distance_To_Hydrology,-0.010515,0.412712,0.040732,-0.055976,1.000000,0.652142,0.203397,-0.033803,0.080047,0.080833,0.158817,-0.009402,0.087484,0.200532,-0.239303
Vertical_Distance_To_Hydrology,0.075647,0.122092,0.056412,0.265314,0.652142,1.000000,0.011555,-0.095930,-0.132948,-0.035559,-0.015048,-0.117835,0.017108,0.069884,0.027321
Horizontal_Distance_To_Roadways,-0.105662,0.578659,0.066184,-0.277049,0.203397,0.011555,1.000000,-0.003398,0.240684,0.173882,0.486386,0.367786,-0.080758,0.124378,-0.440454
Hillshade_9am,-0.010286,0.097900,-0.593997,-0.200072,-0.033803,-0.095930,-0.003398,1.000000,-0.013712,-0.779965,0.078144,0.173382,-0.012096,-0.016736,-0.137192
Hillshade_Noon,-0.098905,0.215782,0.324912,-0.612613,0.080047,-0.132948,0.240684,-0.013712,1.000000,0.614526,0.122098,-0.014362,0.038468,0.188611,-0.203055
Hillshade_3pm,-0.053399,0.089518,0.635022,-0.326887,0.080833,-0.035559,0.173882,-0.779965,0.614526,1.000000,0.043162,-0.119736,0.041908,0.131451,-0.046262
Horizontal_Distance_To_Fire_Points,-0.089389,0.443563,-0.052169,-0.239527,0.158817,-0.015048,0.486386,0.078144,0.122098,0.043162,1.000000,0.430723,0.044781,0.005460,-0.419972
Wilderness_Area1,-0.230117,0.330417,-0.131262,-0.152820,-0.009402,-0.117835,0.367786,0.173382,-0.014362,-0.119736,0.430723,1.000000,-0.103217,-0.475352,-0.373787
Wilderness_Area2,0.014994,0.261729,0.028238,-0.065923,0.087484,0.017108,-0.080758,-0.012096,0.038468,0.041908,0.044781,-0.103217,1.000000,-0.157177,-0.123594
Wilderness_Area3,0.122146,0.354025,0.032578,-0.113033,0.200532,0.069884,0.124378,-0.016736,0.188611,0.131451,0.005460,-0.475352,-0.157177,1.000000,-0.569200
Wilderness_Area4,0.075774,-0.783651,0.075228,0.286985,-0.239303,0.027321,-0.440454,-0.137192,-0.203055,-0.046262,-0.419972,-0.373787,-0.123594,-0.569200,1.000000

In [34]:
a15 = dt[[  "Cover_Type","Soil_Type1","Soil_Type2","Soil_Type3","Soil_Type4","Soil_Type5","Soil_Type6",
            "Soil_Type7","Soil_Type8","Soil_Type9","Soil_Type10","Soil_Type11","Soil_Type12","Soil_Type13",
            "Soil_Type14","Soil_Type15"]]
a15.corr()

x = a15.corr()

res = []

for i in x:
    if x["Cover_Type"].loc[i] > 0:
        res.append(x.loc[i])

res = pd.DataFrame(res)

res

,Cover_Type,Soil_Type1,Soil_Type2,Soil_Type3,Soil_Type4,Soil_Type5,Soil_Type6,Soil_Type7,Soil_Type8,Soil_Type9,Soil_Type10,Soil_Type11,Soil_Type12,Soil_Type13,Soil_Type14,Soil_Type15
Cover_Type,1.000000,0.015069,0.022627,-0.016393,-0.027816,0.027692,0.006521,NaN,-0.008133,-0.027012,0.128972,0.010228,-0.129985,0.040528,0.022019,NaN
Soil_Type1,0.015069,1.000000,-0.032144,-0.040419,-0.037678,-0.016287,-0.032864,NaN,-0.001261,-0.003989,-0.062995,-0.025757,-0.019143,-0.027956,-0.016486,NaN
Soil_Type2,0.022627,-0.032144,1.000000,-0.054037,-0.050373,-0.021775,-0.043937,NaN,-0.001686,-0.005333,-0.084219,-0.034435,-0.025593,-0.037375,-0.022040,NaN
Soil_Type5,0.027692,-0.016287,-0.021775,-0.027380,-0.025524,1.000000,-0.022262,NaN,-0.000854,-0.002702,-0.042673,-0.017448,-0.012968,-0.018937,-0.011168,NaN
Soil_Type6,0.006521,-0.032864,-0.043937,-0.055247,-0.051501,-0.022262,1.000000,NaN,-0.001724,-0.005452,-0.086105,-0.035206,-0.026166,-0.038212,-0.022534,NaN
Soil_Type10,0.128972,-0.062995,-0.084219,-0.105899,-0.098719,-0.042673,-0.086105,NaN,-0.003304,-0.010451,1.000000,-0.067484,-0.050157,-0.073245,-0.043193,NaN
Soil_Type11,0.010228,-0.025757,-0.034435,-0.043300,-0.040364,-0.017448,-0.035206,NaN,-0.001351,-0.004273,-0.067484,1.000000,-0.020508,-0.029948,-0.017661,NaN
Soil_Type13,0.040528,-0.027956,-0.037375,-0.046996,-0.043810,-0.018937,-0.038212,NaN,-0.001466,-0.004638,-0.073245,-0.029948,-0.022258,1.000000,-0.019168,NaN
Soil_Type14,0.022019,-0.016486,-0.022040,-0.027714,-0.025835,-0.011168,-0.022534,NaN,-0.000865,-0.002735,-0.043193,-0.017661,-0.013126,-0.019168,1.000000,NaN

In [35]:
a30 = dt[[  "Cover_Type","Soil_Type16","Soil_Type17","Soil_Type18","Soil_Type19","Soil_Type20",
            "Soil_Type21","Soil_Type22","Soil_Type23","Soil_Type24","Soil_Type25","Soil_Type26",
            "Soil_Type27","Soil_Type28","Soil_Type29","Soil_Type30"]]
a30.corr()

x = a30.corr()

res = []

for i in x:
    if x["Cover_Type"].loc[i] > 0:
        res.append(x.loc[i])

res = pd.DataFrame(res)

res

,Cover_Type,Soil_Type16,Soil_Type17,Soil_Type18,Soil_Type19,Soil_Type20,Soil_Type21,Soil_Type22,Soil_Type23,Soil_Type24,Soil_Type25,Soil_Type26,Soil_Type27,Soil_Type28,Soil_Type29,Soil_Type30
Cover_Type,1.000000,0.008793,0.042453,0.006312,-0.031824,-0.053013,-0.024410,-0.195993,-0.158762,-0.100797,-0.008133,-0.017184,-0.023109,-0.012202,-0.218564,0.001393
Soil_Type16,0.008793,1.000000,-0.017902,-0.005502,-0.004815,-0.008396,-0.002837,-0.013319,-0.020010,-0.011461,-0.000709,-0.005218,-0.002747,-0.002127,-0.026631,-0.019561
Soil_Type17,0.042453,-0.017902,1.000000,-0.012964,-0.011346,-0.019784,-0.006685,-0.031385,-0.047152,-0.027008,-0.001670,-0.012296,-0.006472,-0.005012,-0.062754,-0.046093
Soil_Type18,0.006312,-0.005502,-0.012964,1.000000,-0.003487,-0.006080,-0.002054,-0.009645,-0.014491,-0.008300,-0.000513,-0.003779,-0.001989,-0.001540,-0.019285,-0.014165
Soil_Type30,0.001393,-0.019561,-0.046093,-0.014165,-0.012397,-0.021617,-0.007304,-0.034293,-0.051522,-0.029510,-0.001825,-0.013436,-0.007072,-0.005477,-0.068569,1.000000

In [36]:
a40 = dt[[  "Cover_Type","Soil_Type31","Soil_Type32","Soil_Type33","Soil_Type34","Soil_Type35",
            "Soil_Type36","Soil_Type37","Soil_Type38","Soil_Type39","Soil_Type40"]]
a40.corr()

x = a40.corr()

res = []

for i in x:
    if x["Cover_Type"].loc[i] > 0:
        res.append(x.loc[i])

res = pd.DataFrame(res)

res

,Cover_Type,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
Cover_Type,1.000000,-0.079882,-0.132312,-0.078955,-0.003470,0.114327,0.025726,0.071210,0.257810,0.240384,0.205851
Soil_Type35,0.114327,-0.012348,-0.018021,-0.016984,-0.003146,1.000000,-0.002120,-0.003912,-0.018535,-0.017565,-0.014582
Soil_Type36,0.025726,-0.003855,-0.005625,-0.005302,-0.000982,-0.002120,1.000000,-0.001221,-0.005786,-0.005483,-0.004552
Soil_Type37,0.071210,-0.007113,-0.010381,-0.009784,-0.001812,-0.003912,-0.001221,1.000000,-0.010677,-0.010118,-0.008400
Soil_Type38,0.257810,-0.033699,-0.049181,-0.046350,-0.008585,-0.018535,-0.005786,-0.010677,1.000000,-0.047936,-0.039795
Soil_Type39,0.240384,-0.031935,-0.046606,-0.043924,-0.008136,-0.017565,-0.005483,-0.010118,-0.047936,1.000000,-0.037712
Soil_Type40,0.205851,-0.026512,-0.038692,-0.036465,-0.006754,-0.014582,-0.004552,-0.008400,-0.039795,-0.037712,1.000000

In [37]:
tipo_1 = []
tipo_2 = []
tipo_3 = []
tipo_4 = []
tipo_5 = []
tipo_6 = []
tipo_7 = []

for i in range(0,15120,1):
    if x_treino["Cover_Type"].loc[i] == 1: tipo_1.append(x_treino.loc[i])
    elif x_treino["Cover_Type"].loc[i] == 2: tipo_2.append(x_treino.loc[i])
    elif x_treino["Cover_Type"].loc[i] == 3: tipo_3.append(x_treino.loc[i])
    elif x_treino["Cover_Type"].loc[i] == 4: tipo_4.append(x_treino.loc[i])
    elif x_treino["Cover_Type"].loc[i] == 5: tipo_5.append(x_treino.loc[i])
    elif x_treino["Cover_Type"].loc[i] == 6: tipo_6.append(x_treino.loc[i])
    else: tipo_7.append(x_treino.loc[i])

In [38]:
tipo_1_df = pd.DataFrame(tipo_1)
tipo_2_df = pd.DataFrame(tipo_2)
tipo_3_df = pd.DataFrame(tipo_3)
tipo_4_df = pd.DataFrame(tipo_4)
tipo_5_df = pd.DataFrame(tipo_5)
tipo_6_df = pd.DataFrame(tipo_6)
tipo_7_df = pd.DataFrame(tipo_7)

In [39]:
dt.describe()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
count,15120.00000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,...,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000
mean,7560.50000,2749.322553,156.676653,16.501587,227.195701,51.076521,1714.023214,212.704299,218.965608,135.091997,...,0.045635,0.040741,0.001455,0.006746,0.000661,0.002249,0.048148,0.043452,0.030357,4.000000
std,4364.91237,417.678187,110.085801,8.453927,210.075296,61.239406,1325.066358,30.561287,22.801966,45.895189,...,0.208699,0.197696,0.038118,0.081859,0.025710,0.047368,0.214086,0.203880,0.171574,2.000066
min,1.00000,1863.000000,0.000000,0.000000,0.000000,-146.000000,0.000000,0.000000,99.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,3780.75000,2376.000000,65.000000,10.000000,67.000000,5.000000,764.000000,196.000000,207.000000,106.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,7560.50000,2752.000000,126.000000,15.000000,180.000000,32.000000,1316.000000,220.000000,223.000000,138.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
75%,11340.25000,3104.000000,261.000000,22.000000,330.000000,79.000000,2270.000000,235.000000,235.000000,167.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000
max,15120.00000,3849.000000,360.000000,52.000000,1343.000000,554.000000,6890.000000,254.000000,254.000000,248.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000

In [40]:
tipo_1_df.describe()

,Cover_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
count,2160.0,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.0
mean,1.0,3128.025926,159.463426,13.112963,271.507407,41.281481,2579.715741,211.690278,223.248611,144.065741,1994.412963,0.491667,0.083796,0.424537,0.0
std,0.0,156.124988,117.280496,6.817153,221.250993,55.740461,1495.176212,25.399338,17.975428,36.114843,1249.350813,0.500046,0.277146,0.494387,0.0
min,1.0,2525.000000,0.000000,1.000000,0.000000,-97.000000,108.000000,86.000000,125.000000,0.000000,30.000000,0.000000,0.000000,0.000000,0.0
25%,1.0,3036.000000,54.000000,8.000000,90.000000,4.000000,1380.000000,199.000000,214.000000,122.000000,1080.250000,0.000000,0.000000,0.000000,0.0
50%,1.0,3144.000000,123.000000,12.000000,218.000000,23.000000,2377.000000,216.000000,226.000000,144.000000,1817.500000,0.000000,0.000000,0.000000,0.0
75%,1.0,3234.000000,286.000000,17.000000,395.000000,61.000000,3601.250000,230.000000,236.000000,169.000000,2642.000000,1.000000,0.000000,1.000000,0.0
max,1.0,3675.000000,359.000000,41.000000,1129.000000,411.000000,6508.000000,254.000000,254.000000,246.000000,6993.000000,1.000000,1.000000,1.000000,0.0

In [41]:
tipo_2_df.describe()

,Cover_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
count,2160.0,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.00000,2160.000000,2160.000000,2160.000000
mean,2.0,2922.540278,151.097222,13.423611,287.728704,47.337963,2425.791667,214.044444,225.369907,142.950926,2155.277315,0.52500,0.030556,0.435185,0.009259
std,0.0,185.778268,107.320930,7.038483,215.373206,59.137843,1629.381089,25.033870,18.216843,35.187638,1407.321563,0.49949,0.172150,0.495896,0.095801
min,2.0,2169.000000,0.000000,0.000000,0.000000,-146.000000,30.000000,83.000000,115.000000,6.000000,42.000000,0.00000,0.000000,0.000000,0.000000
25%,2.0,2802.000000,60.000000,8.000000,124.000000,9.000000,1110.000000,202.000000,215.000000,120.000000,1167.000000,0.00000,0.000000,0.000000,0.000000
50%,2.0,2931.500000,125.000000,13.000000,242.000000,31.000000,2023.500000,220.000000,227.000000,141.000000,1851.000000,1.00000,0.000000,0.000000,0.000000
75%,2.0,3042.000000,238.000000,17.000000,404.000000,68.000000,3413.750000,232.000000,239.000000,166.000000,2642.000000,1.00000,0.000000,1.000000,0.000000
max,2.0,3413.000000,359.000000,45.000000,1343.000000,554.000000,6890.000000,254.000000,254.000000,248.000000,6723.000000,1.00000,1.000000,1.000000,1.000000

In [42]:
tipo_3_df.describe()

,Cover_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
count,2160.0,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.0,2160.0,2160.000000,2160.000000
mean,3.0,2398.423148,173.672685,20.628704,210.723148,64.081944,969.595833,201.655556,216.561111,141.549537,916.909722,0.0,0.0,0.399537,0.600463
std,0.0,194.108147,108.013267,8.888591,142.053957,58.333807,620.000509,40.366706,27.519785,51.582375,532.464556,0.0,0.0,0.489917,0.489917
min,3.0,1903.000000,0.000000,1.000000,0.000000,-115.000000,0.000000,58.000000,120.000000,0.000000,30.000000,0.0,0.0,0.000000,0.000000
25%,3.0,2270.000000,86.000000,14.000000,90.000000,19.000000,480.000000,173.000000,200.000000,106.000000,514.000000,0.0,0.0,0.000000,0.000000
50%,3.0,2409.000000,161.000000,21.000000,190.000000,51.000000,897.000000,212.000000,222.000000,142.000000,828.000000,0.0,0.0,0.000000,1.000000
75%,3.0,2551.000000,277.000000,27.000000,306.000000,97.000000,1318.000000,235.000000,238.000000,180.000000,1200.000000,0.0,0.0,1.000000,1.000000
max,3.0,2850.000000,360.000000,47.000000,700.000000,275.000000,3181.000000,254.000000,254.000000,248.000000,2846.000000,0.0,0.0,1.000000,1.000000

In [43]:
tipo_4_df.describe()

,Cover_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
count,2160.0,2160.00000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.0,2160.0,2160.0,2160.0
mean,4.0,2223.42037,138.099537,18.468519,104.537500,40.143519,915.100463,227.968056,216.889815,111.808796,860.540741,0.0,0.0,0.0,1.0
std,0.0,102.92994,88.846589,9.361156,138.452917,58.343108,361.208979,24.288340,21.006249,49.383949,482.990176,0.0,0.0,0.0,0.0
min,4.0,1989.00000,0.000000,1.000000,0.000000,-25.000000,67.000000,127.000000,137.000000,0.000000,0.000000,0.0,0.0,0.0,1.0
25%,4.0,2140.00000,82.000000,10.000000,0.000000,0.000000,629.000000,215.000000,204.000000,74.000000,459.000000,0.0,0.0,0.0,1.0
50%,4.0,2230.50000,119.000000,18.000000,30.000000,6.000000,942.000000,234.000000,220.000000,114.000000,808.000000,0.0,0.0,0.0,1.0
75%,4.0,2304.25000,162.000000,26.000000,192.000000,69.000000,1207.000000,249.000000,231.000000,150.000000,1256.000000,0.0,0.0,0.0,1.0
max,4.0,2526.00000,359.000000,46.000000,551.000000,270.000000,1702.000000,254.000000,254.000000,230.000000,1921.000000,0.0,0.0,0.0,1.0

In [44]:
tipo_5_df.describe()

,Cover_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
count,2160.0,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.0,2160.000000,2160.0
mean,5.0,2786.801389,137.992130,16.724537,208.873148,50.871296,1329.318519,223.368981,218.317130,121.392593,1530.388889,0.396296,0.0,0.603704,0.0
std,0.0,96.177469,91.772285,8.440048,179.159524,58.463641,1041.100986,22.487451,25.980805,50.121931,976.589203,0.489241,0.0,0.489241,0.0
min,5.0,2482.000000,0.000000,1.000000,0.000000,-134.000000,30.000000,130.000000,99.000000,0.000000,60.000000,0.000000,0.0,0.000000,0.0
25%,5.0,2729.000000,69.000000,10.000000,85.000000,5.000000,420.000000,211.000000,204.000000,84.000000,850.000000,0.000000,0.0,0.000000,0.0
50%,5.0,2793.000000,108.000000,16.000000,170.000000,35.000000,1253.500000,228.000000,224.000000,128.000000,1432.000000,0.000000,0.0,1.000000,0.0
75%,5.0,2856.000000,192.000000,22.000000,295.000000,82.000000,1956.000000,241.000000,238.000000,158.000000,1933.500000,1.000000,0.0,1.000000,0.0
max,5.0,3007.000000,359.000000,50.000000,1082.000000,262.000000,5198.000000,254.000000,254.000000,229.000000,6279.000000,1.000000,0.0,1.000000,0.0

In [45]:
tipo_6_df.describe()

,Cover_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
count,2160.0,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.000000,2160.0,2160.0,2160.000000,2160.000000
mean,6.0,2423.276852,180.617130,18.986111,160.095370,44.873611,1064.980556,193.562963,209.960648,147.682407,1057.654167,0.0,0.0,0.445370,0.554630
std,0.0,188.966981,133.087862,7.714618,125.770515,47.034674,576.384899,33.684031,23.934851,45.588500,576.691004,0.0,0.0,0.497122,0.497122
min,6.0,1863.000000,0.000000,1.000000,0.000000,-104.000000,0.000000,0.000000,127.000000,22.000000,0.000000,0.0,0.0,0.000000,0.000000
25%,6.0,2319.750000,44.000000,13.000000,60.000000,7.000000,626.000000,169.000000,195.000000,114.000000,643.500000,0.0,0.0,0.000000,0.000000
50%,6.0,2430.000000,171.000000,19.000000,134.000000,33.000000,993.000000,196.000000,213.000000,150.000000,942.000000,0.0,0.0,0.000000,1.000000
75%,6.0,2553.000000,318.000000,24.000000,240.000000,73.000000,1420.500000,221.000000,227.000000,184.000000,1364.250000,0.0,0.0,1.000000,1.000000
max,6.0,2883.000000,360.000000,52.000000,624.000000,249.000000,3078.000000,254.000000,254.000000,238.000000,2918.000000,0.0,0.0,1.000000,1.000000

In [46]:
tipo_7_df.describe()

tipo_7_df.corr()

,Cover_Type,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Wilderness_Area1,Wilderness_Area2,Wilderness_Area3,Wilderness_Area4
Cover_Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Elevation,NaN,1.000000,0.095373,-0.085583,0.410053,0.425085,0.187708,-0.170297,0.001724,0.150004,0.129789,-0.261181,0.277296,0.050616,NaN
Aspect,NaN,0.095373,1.000000,-0.015894,0.125168,0.066620,0.113614,-0.583490,0.286829,0.587363,0.062640,-0.138813,0.010844,0.117736,NaN
Slope,NaN,-0.085583,-0.015894,1.000000,-0.061672,0.166451,-0.022778,-0.011679,-0.635155,-0.499847,-0.070833,-0.046901,-0.020112,0.055598,NaN
Horizontal_Distance_To_Hydrology,NaN,0.410053,0.125168,-0.061672,1.000000,0.756085,0.030289,-0.186677,0.070656,0.197174,-0.046018,-0.273636,-0.015712,0.256762,NaN
Vertical_Distance_To_Hydrology,NaN,0.425085,0.066620,0.166451,0.756085,1.000000,0.096025,-0.181634,-0.095436,0.065701,0.020956,-0.230274,-0.008546,0.212963,NaN
Horizontal_Distance_To_Roadways,NaN,0.187708,0.113614,-0.022778,0.030289,0.096025,1.000000,-0.197484,0.075662,0.198288,0.639390,0.112130,-0.428025,0.183829,NaN
Hillshade_9am,NaN,-0.170297,-0.583490,-0.011679,-0.186677,-0.181634,-0.197484,1.000000,-0.007885,-0.767091,-0.117809,0.182777,-0.064665,-0.121503,NaN
Hillshade_Noon,NaN,0.001724,0.286829,-0.635155,0.070656,-0.095436,0.075662,-0.007885,1.000000,0.623274,-0.019084,-0.044257,-0.032991,0.061786,NaN
Hillshade_3pm,NaN,0.150004,0.587363,-0.499847,0.197174,0.065701,0.198288,-0.767091,0.623274,1.000000,0.099566,-0.153885,0.037965,0.113259,NaN
Horizontal_Distance_To_Fire_Points,NaN,0.129789,0.062640,-0.070833,-0.046018,0.020956,0.639390,-0.117809,-0.019084,0.099566,1.000000,0.317395,-0.212272,-0.144475,NaN
Wilderness_Area1,NaN,-0.261181,-0.138813,-0.046901,-0.273636,-0.230274,0.112130,0.182777,-0.044257,-0.153885,0.317395,1.000000,-0.211117,-0.759680,NaN
Wilderness_Area2,NaN,0.277296,0.010844,-0.020112,-0.015712,-0.008546,-0.428025,-0.064665,-0.032991,0.037965,-0.212272,-0.211117,1.000000,-0.475258,NaN
Wilderness_Area3,NaN,0.050616,0.117736,0.055598,0.256762,0.212963,0.183829,-0.121503,0.061786,0.113259,-0.144475,-0.759680,-0.475258,1.000000,NaN
Wilderness_Area4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

A PARTIR DAQUI COMEÇAM OS TESTES, ACIMA SÓ FOI PREPARADO PARA ANÁLISE!!!

Abaixo será testado o modelo de decision trees

In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [48]:
variaveis = [   'Elevation','Aspect', 'Slope', 'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Hydrology', 'Horizontal_Distance_To_Fire_Points',
                "Horizontal_Distance_To_Roadways",'Hillshade_3pm','Wilderness_Area2','Wilderness_Area3','Wilderness_Area4',"Soil_Type1", "Soil_Type2", "Soil_Type5",
                "Soil_Type6", "Soil_Type10","Soil_Type11",  "Soil_Type13", "Soil_Type14", "Soil_Type16", "Soil_Type17", "Soil_Type18", "Soil_Type30",
                "Soil_Type35", "Soil_Type36", "Soil_Type37", "Soil_Type38", "Soil_Type39", "Soil_Type40" ]

In [49]:
x = dt[variaveis]
y = dt["Cover_Type"]

In [50]:
x_prev = dt[variaveis]

Abaixo será feito arquivos falsos baseados nos dados originais, em cada seed será feito novos arquivos aleatórios para teste. Desta forma é possível testar a a média de acertos.

In [51]:
dados_falsos = np.arange(50000)
dados_falsos

array([    0,     1,     2, ..., 49997, 49998, 49999])

In [59]:
np.random.seed()   #Ter sempre o mesmo valor no teste, memso sendo aleatório

x_treino, x_valid, y_treino, y_valid = train_test_split(x, y, test_size=0.5)

In [60]:
modelo = RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=0)
modelo.fit(x_treino, y_treino)

RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=0)

In [61]:
a = modelo.predict(x_valid)
np.mean(y_valid == a)

0.8457671957671957

Após criar a arvore de decisão, será testado no arquivo "test"

In [62]:
x_prev = test[variaveis]
p = modelo.predict(x_prev)

In [63]:
prev_final = pd.Series(p, index=test['Id'], name="Cover_Type")

In [64]:
prev_final.to_csv("Resultado_Final.csv", header=True)
!head n10 Resultado_Final.csv

==> Resultado_Final.csv <==
Id,Cover_Type
15121,2
15122,2
15123,2
15124,2
15125,2
15126,2
15127,2
15128,2
15129,2

head: cannot open 'n10' for reading: No such file or directory

In [65]:
prev_final

Id
15121     2
15122     2
15123     2
15124     2
15125     2
         ..
581008    3
581009    3
581010    3
581011    3
581012    3
Name: Cover_Type, Length: 565892, dtype: int64